### PR TITLE
make: select SDL version

### PR DESCRIPTION
**Pull request by greisch**
Debian unstable, not working SDL2 (at least for me) ; but work SLD1.2

### CODE REVIEW

**Comment by greisch** [comment]
Checked. Actualy is a BUG in mupen64plus-input-sdl
mame (1:0.164-dmo1) => use SDL2 (2.0.2) and Joystick work
stella (4.6.1-2) => use SDL2 (2.0.2) and Joystick work
nestopia (1.46.2-1) => use SDL2 (2.0.2) and Joystick work

I download and compile SDL2 (2.0.3) and same problem whit mupen64plus-input-sdl
I download and compile SDL2 (2.0.2), compile test applications and "./testjoystick" detect the name and capabilities correctly, also "./testhaptic" detect correct name and ForceFeedback capabilites also. Sow problem should be in mupen64plus-input-sdl code.

Where can I generate the BUG ? because google.code is goin down :-P ?

**Comment by richard42** [comment]
Is it a build problem, or a runtime problem?  Can you describe the problem in more detail and give a listing of all the console output?

**Comment by greisch** [comment]
Ok, My fault! Its a runtime problem, and it's SDL fault! (and my)
I have mupen64plus (user interface + core) compiled whit  SDL1.2 , but the plugin mupen64plus-input-sdl whit SDL2.0 sow.... When call to function SDL_JoystickName(id) it return NULL!
If compile [core+interface] whit SDL2 and mupen64plus-input-sdl whit SDL1.2 the same problem! Return string "(null)".

If compile all whit the same version of SDL then WORK!!!  :-)

This is a problem if you have third party plugins outside of mupen64plus source code..... I will report this to SDL  :-/

**Comment by conchurnavid** [comment]
I doubt they will change anything. It was their design decision to only allow on single, global SDL context. Having two different (incompatible) ones is just not allowed and cannot be fixed easily without doing a major redesign of anything in SDL

**Comment by greisch** [comment]
No, they not change anything. Reported and closed WONTFIX  , jejej :-P

**Pull request closed without merging**
