### PR TITLE
Correctly manage SDL subsystems

### PR DESCRIPTION
**Pull request by Henrik0x7F**
I'm creating a frontend for Mupen64Plus and I'm also using SDL for various things. I noticed Mupen64Plus uses SDL in a very "egoistical" way: Subsystems are shutdown even if they were already initialized before Mupen64Plus tried to intialize them. This is a big pain if the frontend also wants to use SDL but subsystems are shutdown by the emulator.

I changed the way the input plugin handles SDL subsystems but this problem also persists in other plugins (and the core). Are you open for these changes? If so can I also fix the SDL usage in the other modules?

### CODE REVIEW

**Comment by Henrik0x7F** [comment]
In general, who is the one initializing and shutting down SDL systems in mupen64plus? If every plugin has to be adapted to work with the frontend compatibility would suffer a lot. What do you think, should I just override `SDL_Init`, `SDL_InitSubsystem`, `SDL_Quit` and `SDL_QuitSubsystem` with LD_PRELOAD to reference count? On windows this isn't a problem since the plugins link to a different SDL.dll than the frontend.

**Comment by richard42** [comment]
Regarding SDL system init/shutdown, it's basically a free for all. There is no centralized management of this; it's every module for itself. It's not something that I designed for or considered. At the beginning, there weren't very many plugins, I was working on the source code for all of them, and they all used SDL.  Since then, a lot has happened.

I would not recommend overriding the SDL init/quit functions with LD_PRELOAD; that always feels like a hack of last resort. I would say that the design policy going forward should be that the plugins init and shut down SDL subsystems in a not-egotistical (courteous) way at appropriate times (ROM open/close maybe?) so they don't cause problems for the front-end application.  The video subsystem may be a special case because of the mupen64plus video extension mechanism that's built into the API.

I would also think that the core and plugins should all link against the same SDL.dll shared library at run time. Does that not cause problems under Windows, to have them pulling in different libraries?

**Comment by Henrik0x7F** [comment]
On windows it doesn't seem to quit the subsystems. I assumed that's because you ship SDL.dll on windows while relying on the system SDL on linux. So you're working with "your copy" of SDL's global state. It also turns out that SDL subsystems are already refcounted. SDL_Quit() is the exception: It forces the shutdown no matter the refcount. So to fix all this it's would only be necessary to remove the SDL_Quit() from the core.

**Comment by Henrik0x7F** [comment]
I personally think the best way to deal with this is to check if any SDL component was initialized in `CoreStartup` and only then call SDL_Quit() in `CoreShutdown`. I'll open a pull request in the next few days.

**Pull request merged**
